import "@/styles/globals.css";
import { Providers } from "@/components/providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen ">
        <Providers>
          <div className="mx-auto flex max-w-[1400px]">
            <header className="sticky top-0 h-screen basis-40">
              <div className="">header</div>
            </header>

            <main className="flex-1 border-l-2 border-r-2">{children}</main>

            <footer className="sticky top-0 basis-60 h-screen">
              <div>footer</div>
            </footer>
          </div>
        </Providers>
      </body>
    </html>
  );
}
